config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'start' => 'questions#start_scene'
  post '/next_scene' => 'questions#next_scene'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless session[:scene_id].nil?
      @question = Question.find_by(scene_id: session[:scene_id])
      @answers = @question.answers
    else 
      session[:scene_id] = 1
      @question = Question.find_by(scene_id: session[:scene_id])
      @answers = @question.answers
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def start_scene
    @question = Question.find_by(scene_id: 1) 
    @answers = @question.answers
  end

  def next_scene
    if session[:scene_count].nil?
      session[:scene_count] = 1
    else
      session[:scene_count] += 1
    end
    
    if session[:scene_id].nil?
      session[:scene_id] = 1
      @question = Question.find_by(scene_id: 1)
      @answers = @question.answers
    else
      if session[:scene_id] == "17"
        session[:scene_count] = 1
      end 
      @id = "#{session[:scene_id]}_#{params[:scene_id]}"
      session[:scene_id] = params[:scene_id]
      @question = Question.find_by(scene_id: params[:scene_id])
      @answers = @question.answers
    end

    respond_to do |format|
      format.js{}
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_serkol_count.html.erb
<% serkol_count = 12 %>

<% if session[:scene_count].nil? %>
  <% (0...serkol_count).each do |i| %>
    <%= image_tag("serkol-07.png", :alt => "Your progress through the day", id: 'serkol-1') %>
  <% end %>
<% else %>
  <% (0...session[:scene_count]).each do |i| %>
    <%= image_tag("serkol-08.png", :alt => "Your progress through the day", id: 'serkol-1') %>
  <% end %>

  <% (0...(serkol_count - session[:scene_count])).each do |i| %>
    <%= image_tag("serkol-07.png", :alt => "Your progress through the day", id: 'serkol-1') %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script>
        var x = $("#min");   
        document.addEventListener("click", function (e){
            if (x.style.webkitAnimationPlayState === "paused")
            {
                x.style.webkitAnimationPlayState = "running";
            }
            else
            {
                x.style.webkitAnimationPlayState = "paused";
            }, false);
        })
    </script>

<script type="text/javascript">
    $(window).load(function(){
        $('#welcome').modal('show');
    });

</script>

<script type="text/javascript">
    function one(){
        $("#filipinoTime").modal("show");
    }

    function two(){
        $("#bahalaNa").modal("show");
    }
</script>

<!-- Modal -->
<div class="modal fade in" id="welcome" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Welcome to Juan Day</h4>
            </div>
            <div class="modal-body">
                <p> Hello! This is Juan Day, where we try to simulate what it feels like to live within Filipino Culture! Throughout the quiz, you'll be faced with mundane situations within the Filipino setting where our flaws as a society shall be made more apparent. The choice lies in your hands whether you'll cultivate this "culture" or take action to try and change it.</p>
            </div>
        </div>
    </div>
</div>
<!-- end of modal -->

<!-- First Modal: Filipino Time -->
<div class="modal fade in" id="filipinoTime" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Filipino Time</h4>
            </div>
            <div class="modal-body">
                <p> Filipinos like to put things off generally at a later date because Filipinos are timeless; they do not have exact definitions regarding time.</p>
            </div>
        </div>
    </div>
</div>

<div class="modal fade in" id="bahalaNa" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Bahala Na</h4>
            </div>
            <div class="modal-body">
                <p> Filipinos are very spiritual, and they tend to rely on deities instead of taking responsibility for their own decisions, which is why the term "Bahala na" came to fame. Bahala came from the old Filipino word "Bathala" which means God.</p>
            </div>
        </div>
    </div>
</div>
<!-- end Filipino Time -->

<div id=core class="col-md-10">
    <div class="header"  id="main">
        <%= image_tag("icon1.png", :alt => "Juan Day", id: 'icon1') %>
    </div>
    <div id="content">
      <% if session[:scene_id].nil? %>
        <% session[:scene_id] = 1 %>
        <%= render 'questions/scene_1' %>
      <% else %>
        <%= render "questions/scene_#{session[:scene_id]}" %>
      <% end %>
    </div>

    <div id="progress">
      <%= render 'home/serkol_count' %>
    </div>
</div>

<div id="sidebar" class="col-md-2">
    <div class="clock" id="square">
        <ul class="clock" id="square">
          <li id="sec"></li>
          <li id="hour"></li>
          <li id="min"></li>
        </ul>
    </div>


    <div>
        <%= image_tag("utils.png", :alt => "Money") %> UTILS
    </div>
    
    <div>
        <div class="progress">
            <div class="progress-bar" role="progressbar" id="utility" aria-valuenow="70"
            aria-valuemin="0" aria-valuemax="100" style="width:70%">
            70%
            </div>
        </div>
    </div>
    
    <br/>
    
    <div>
        <%= image_tag("energy.png", :alt => "Money") %> UTILS
    </div>
    
    <div>
        <div class="progress">
            <div class="progress-bar progress-bar-warning" role="progressbar", id="energy" aria-valuenow="70"
            aria-valuemin="0" aria-valuemax="100" style="width:70%">
            70%
            </div>
        </div>
    </div>

    <br/>
    
    <div>
        <%= image_tag("money.png", :alt => "Money") %> UTILS
    </div>
    
    <div>
        <div class="progress">
            <div class="progress-bar progress-bar-danger" role="progressbar", id="money" aria-valuenow="70"
            aria-valuemin="0" aria-valuemax="100" style="width:70%">
            70%
            </div>
        </div>
    </div>
  </div>

app/views/home/index.js.erb
$('#content').html("<%= j render 'questions/scene_1' %>");
$('#progress').html("<%= j render 'home/serkol_count' %>");

app/views/layouts/_navbar.html.erb
<nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Juan Day</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway'></stylesheet_link_tag>
    <stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Droid+Serif'></stylesheet_link_tag>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <%= yield %>

</body>
</html>

app/views/questions/_scene_1.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("1.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_10.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("10.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_11.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("11.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_13.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("13.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_14.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("14.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_15.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("15.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_18.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("14.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_2.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("2.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_3.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("3.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_5.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("5.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_6.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("6.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_8.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("8.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/_scene_9.html.erb
<div class="panel panel-default" id="expander">
    <div class="panel-body">
        <div class="col-md-8">
          <%= image_tag("9.jpg", :alt => "Your scenario", id: 'scenario') %>
        </div>     
        <div id="questionanswer" class="col-md-4">
          <h1 id="question"> <%= @question.text %></h1> <br>

          <% @answers.each_with_index do |answer, i| %>
              <%= button_to "#{answer.text}", next_scene_path(scene_id: answer.scene_id), remote: true, class: "btn btn-default choice", id: "#{@question.scene_id}_#{answer.scene_id}", 
                style: 'white-space: normal;' %>
              <br>
          <% end %>
        </div>
    </div>
</div>

app/views/questions/next_scene.js.erb
<% scene = "questions/scene_#{session[:scene_id]}" %>
$('#content').html("<%= j render scene %>");
$('#progress').html("<%= j render 'home/serkol_count' %>");

    console.log('clicked');
    var bar = Math.floor(1 + Math.random() * 3);
    var val = Math.floor(1 + (Math.random() * 100)) + '%';

    var curr_energy = parseInt($('#energy').text());
    var curr_utility = parseInt($('#utility').text());
    var curr_money = parseInt($('#money').text());

    var add = Math.floor(2 + (Math.random() * 10))

    <% utility_energy = ["1_2", "3_2"] %>
    <% energy = ["3_4", "1_3"] %>

    if(Math.round(Math.random()) == 0) {
      add = (-1)*add;
    }

<% if @id == "1_2" %>
   $(window).load(function(){
     $('#filipinoTime').modal('show');
   });
<% elsif @id == "1_3" %>
   $(window).load(function(){
     $('#filipinoTime').modal('show');
   });
<% end %>


<% if utility_energy.include?(@id) %>
  $('#utility').width((curr_utility+add)+'%').text((curr_utility+add)+'%');
  $('#energy').width((curr_energy+add)+'%').text((curr_energy+add)+'%');
<% elsif energy.include?(@id) %>
  $('#energy').width((curr_energy+add)+'%').text((curr_energy+add)+'%');
<% elsif @id == "17_1" %>
  $('#utility').width('70%').text('70%');
  $('#energy').width('70%').text('70%');
  $('#money').width('70%').text('70%');
<% else %>
  switch (bar) {
    case 1:
      $('#utility').width(val).text(val);
      break;
    case 2:
    $('#energy').width(val).text(val);
      break;
    case 3:
      $('#money').width(val).text(val);
      break;
  }
<% end %>